version: "3"

tasks:
  build:
    cmds:
      - go build -o bin/app main.go

  test:
    cmds:
      - go test ./...

  testv:
    cmds:
      - go test -v ./...

  test-clean:
    cmds:
      - go clean -testcache

  default:
    deps: [build, test]
